### ISSUE TITLE
Error on running the module on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by shubham-root** [sindresorhus/default-browser-cli#2]
**Summary**
`default-browser` command fails with `ExperimantalWarning: The ESM module loader is experimental`

**System:**
NodeJS 12.18.3; NVM 6.14.8; installed with NVM 0.35.3

**Steps to Reproduce**
- `$ npm install -g default-browser-cli`
- `$ default-browser`

**Expected Response**
`Google Chrome`

**Obtained Response**
```
ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: require is not defined
    at defaultBrowser (file:///home/user/.nvm/versions/node/v12.18.3/lib/node_modules/default-browser-cli/node_modules/default-browser/index.js:7:3)
    at file:///home/user/.nvm/versions/node/v12.18.3/lib/node_modules/default-browser-cli/cli.js:12:23
    at file:///home/user/.nvm/versions/node/v12.18.3/lib/node_modules/default-browser-cli/cli.js:14:3
    at ModuleJob.run (internal/modules/esm/module_job.js:139:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

**Comment by sindresorhus** [comment]
Make sure you're on the latest minor version of Node.js 12.
